<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
//    'Activation email' => '',
//    'This email has already beМова en taken.' => '',
//    'Your account has been successfully activated.' => '',
//    'Your account has been successfully created. Check your email for further instructions.' => '',
//    'Your activation link: {url}' => '',
//    'About' => 'О нас',
//    'Account Settings' => 'Налаштування аккаунта',
//    'Articles' => 'Статті',
//    'Attachments' => 'Вкладення',
//    'Backend' => 'Панель управління',
//    'Body' => 'Повідомлення',
//    'Check your email for further instructions.' => 'Перевірте ваш e-mail.',
//    'Confirm Password' => 'Підтвердження пароля',
//    'Contact' => 'Контакти',
//    'E-mail' => 'E-mail',
//    'Email' => 'Email',
//    'Error while oauth process.' => 'Помилка під час OAuth авторизації.',
//    'Female' => 'Жіноча',
//    'Home' => 'Головна',
//    'If you forgot your password you can reset it <a href="{link}">here</a>' => 'Якщо ви забули свій пароль, ви можете скинути його <a href="{link}">тут</a>',
//    'Incorrect username or password.' => 'Неправильні им’я користувача або пароль',
//    'Language' => 'لغة',
//    'Log in with' => 'Увійти за допомогою',
//    'Login' => 'Вхід',
//    'Logout' => 'Вихід',
//    'Male' => 'Чоловіча',
//    'Name' => 'Ім’я',
//    'Need an account? Sign up.' => 'Потрібен аккаунт? Зареєструйтесь',
//    'New password was saved.' => 'Новий пароль було збережено',
//    'Page not found' => 'Сторінка не знайдена',
//    'Password' => 'Пароль',
//    'Password reset for {name}' => 'Скидання пароля для {name}',
//    'Profile settings' => 'Налаштування профілю',
//    'Remember Me' => 'Запом’ятати мене',
//    'Request password reset' => 'Запит на скидання пароля',
//    'Reset password' => 'Скидання пароля',
//    'Settings' => 'Налаштування',
//    'Sign up with' => 'Створити аккаунт за допомогою',
//    'Signup' => 'Реєстрація',
//    'Sorry, we are unable to reset password for email provided.' => 'Вибачте, але ми не можемо скинути пароль для цього e-mail.',
//    'Subject' => 'Тема',
//    'Submit' => 'Відправити',
//    'Thank you for contacting us. We will respond to you as soon as possible.' => 'Дякуэмо. Ми відповімо Вам якнайшвидше.',
//    'There was an error sending email.' => 'Сталася помилка при відправці email',
//    'This email address has already been taken.' => 'Цей e-mail вже зайнятий',
//    'This username has already been taken.' => 'Це им\'я користувача вже використовується',
//    'Update' => 'Зберегти',
//    'User Settings' => 'Налаштування користувача',
//    'Username' => 'Им\'я користувача',
//    'Username or email' => 'Им’я користувача або e-mail',
//    'Verification Code' => 'Код перевірки',
//    'We already have a user with email {email}' => 'Користувач с e-mail {email} вже зареэстрований',
//    'Welcome to {app-name}. Email with your login information was sent to your email.' => 'Вітаємо у {app-name}. Вам був надісланий e-mail с інформациєю щодо користувача',
//    'Your account has been successfully saved' => 'Ваш аккаунт було успішно збережено',
//    '{app-name} | Your login information' => '{app-name} | Інформація про користувача',
//





    'New Concept In the world of Equestrian and Entertainment'	 => 'مفهوم جديد في عالم الفروسية و الترفيه',
  'EXCELLENCE AND LEADERSHIP IN THE WORLD OF EQUESTRIAN'	 =>'تميز و ريادة في عالم الفروسية',
 'Vision'	 =>'الرؤية',
'A team of experienced equestrian experts has conducted a field survey and extensive studies that resulted from the creation of the idea of a world-class equestrian resort project that combines originality, modernity and entertainment with a distinctive social environment.'	 =>'قام فريق متميز, ذو خبرة طويلة في مجال الفروسية بمسح ميداني و دراسات مكثفة نتجت عن ابتكار فكرة مشروع عالمي منتجع الفروسيةالعالمي يمزج ما بين الاصالة و الحداثة و الترفيه الهادف في بيئة إجتماعية راقية و متميزة',

'Our Services'	 =>	'خدماتنا',
'Horse Riding'	 =>'االفروسية',
'special courses for riding with specialized trainers. and acadamic courses'	 =>'دورات فروسية خاصة من قبل مدربات عالميات و بطريقة التدريب الاكاديمي لضمان تحقيق اعلى المستويات',
'Private Riding'	 =>	'خدمات الفروسية الخاصة',
'Host your Horse at our facility and enjoy our wide range of services'	 =>'نستضيف الخيول الخاصة بالمشتركات و نقوم بالرعاية الصحية و الطبية لهم مع خدمات التدريب الخاص',
'Fitness Center'	 =>'مركز لياقة',
'GYM excersice and fitness lounge in partnership with Technogym with a direct view to Horse yards'	 =>	'صالة التمرين و الرياضة GYM بالشراكة مع Technogymمع اطلاله مباشرة على ميادين الخيل',
'Nails & SPA'	 =>	'Nails & SPA',
'Pedicure and Mancure specialized in the highest level of professional and experience.'	 =>'بديكير و منيكير بايدي متخصصة على أعلى مستوى من الاحتراف و الخبرة',
'Prevention & Osteopathic Center'	 =>	'ﻣﺮﻛﺰ ﻧﻘﺎﻫﻪ',
'With  collaboration with MYO Osteopathy center'	 =>	'مركز نقاهة بأعلى المعايير الوقائية بالتعاون مع مركز مايو اوستيوباثي',
'YOGA'	 =>	'يوغا',
'Special courses of YOGA sport in the beautifull enviroment of our Resort'	 =>	'دروس خاصة في رياضة اليوغا مع مدربات مختصات في مجال الرياضة التدريب',
'Steps'	 =>'خطوات الانضمام',
'How to become One of Our Lucky members'	 =>	'كيفية الترشح للعضوية في منتجع الفروسية العالمي',
'Apply request'	 =>	'تقديم الطلب',
'Apply a request online with all <br>info needed<br>press apply to apply'	 =>'تقديم طلب عبر الإنترنت مع جميع المعلومات اللازمة',
'Request Study'	 =>'دراسة الطلب',
"Your Request will be studed inorder to&nbsp;<br>have all the needed terms<br>and conditions"	 =>'سوف نقوم بدراسة الطلب لاستيفاء جميع الشروط اللازمة لتكوني عضوة في نادي الفروسة العالمي و سوف يتم اعلامك بذلك',
'Payment'	 =>	'اتمام المستحقات',
"Make the payment fees&nbsp;<br>according to your Membership<br>type"	 =>	'اتمام دفع المستحقات السنوية للعضوية مع ادارة المبيعات لدينا و بحسب نوع العضوية',
'Recieve Card'	 =>'الحصول على بطاقة العضوية',
"Recieve the membership Card
                            <br>and user access"	 =>'الحصول على بطاقة العضوية و التمتع بخدمات نادي الفروسية العالمي',
'CONTACT IE RESORT'	 =>'تواصل مع منتجع الفروسية العالمي',
'CONTACT INFO'	 =>'تواصل معنا',
'Where to Find Us'	 =>	'العنوان',
'Email Us At'	 =>'الايميل',
'Call Us At'	 =>'رقم الاتصال',
'Phone:'	 =>'جوال',
'Menu'	 =>'القائمة',
'Navigation'	 =>'تصفح القائمة',
'Home'	 =>	'الرئيسية',
'About'	 =>	'عن المنتجع',
'Services'	 =>	'الخدمات',
'Terms and Condition'	 =>	'الشروط و الاحكام',
'Register'	 =>	'طلب العضوية',
'Login'	 => 'login',
'English'	 =>	'English'




];
